---
title: "disparity report"
author: "Tomas Corey"
date: "August 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(msm)
library(dplyr)
library(Epi)
library(ggplot2)
library(plyr)
library(survival)
```

## Defining Functions


``` {r functions, echo = FALSE}
get_rate_matrices <- function(dat){
  mapply(FUN = function(inc, surv){
    matrix(c(-inc, inc, 0, 0, -surv, surv, 0, 0, 0), nrow = 3, byrow = TRUE)
  }, inc = dat$incrate, surv = dat$survrate, SIMPLIFY = FALSE)
}

find_prob_matrix <- function(start_time, end_time, breakpts, rates){
  marked_times <- sort(c(breakpts, start_time, end_time))
  marked_times <- marked_times[marked_times >= start_time & marked_times <= (end_time)]
  mapping <- approx(x = breakpts, 
                    y = 1:length(breakpts),
                    xout = marked_times, 
                    method = "constant",
                    rule = 2)
  lengths_spent <- diff(mapping$x)
  ind_matrices <- mapping$y[-(length(mapping$y))]
  rates_list <- mapply(MatrixExp, rates[ind_matrices], lengths_spent, SIMPLIFY = FALSE)
  mat <- matrix(0, nrow(rates[[1]]), ncol(rates[[1]]))
  diag(mat) <- 1
  for(new_mat in rates_list){
    mat <- mat %*% new_mat
  }
  return(mat)
}

find_density <- function(the_time, birth_year, c, breakpts, oldrates, newrates){
  
## 
    
  pmat_c <- find_prob_matrix(start_time = 0, 
                            end_time = c - birth_year,  
                            breakpts = breakpts,
                            rates = oldrates)
  pmat_t <- find_prob_matrix(start_time = 0, 
                            end_time = the_time - birth_year,  
                            breakpts = breakpts,
                            rates = oldrates)
  pmat_t_c <- find_prob_matrix(start_time = c - birth_year, 
                              end_time = the_time - birth_year,  
                              breakpts = breakpts,
                              rates = oldrates)
  pmat_t_c_new <- find_prob_matrix(start_time = c - birth_year, 
                                  end_time = the_time- birth_year,  
                                  breakpts = breakpts,
                                  rates = newrates)
  ind <- approx(x = breakpts, 
                    y = 1:length(breakpts),
                    xout = (the_time - birth_year), 
                    method = "constant",
                    rule = 2)
  oldrate <- oldrates[[ind$y]]
  newrate <- newrates[[ind$y]]
  if(the_time<c){
    dens=pmat_t[1,2]*oldrate[2,3]  
  }else{
    dens=pmat_c[1,2]*pmat_t_c[2,2]*oldrate[2,3]+pmat_c[1,1]*pmat_t_c_new[1,2]*newrate[2,3]
  }
  return(dens)
}

find_cdf <- function(the_time, birth_year, c, breakpts, oldrates, newrates){
  
  pmat_c <- find_prob_matrix(start_time = 0, 
                            end_time = c - birth_year,  
                            breakpts = breakpts,
                            rates = oldrates)
  pmat_t <- find_prob_matrix(start_time = 0, 
                            end_time = the_time - birth_year,  
                            breakpts = breakpts,
                            rates = oldrates)
  pmat_t_c <- find_prob_matrix(start_time = c - birth_year, 
                              end_time = the_time - birth_year,  
                              breakpts = breakpts,
                              rates = oldrates)
  pmat_t_c_new <- find_prob_matrix(start_time = c - birth_year, 
                                  end_time = the_time- birth_year,  
                                  breakpts = breakpts,
                                  rates = newrates)
  ind <- approx(x = breakpts, 
                y = 1:length(breakpts),
                xout = (the_time - birth_year), 
                method = "constant",
                rule = 2)
  oldrate <- oldrates[[ind$y]]
  newrate <- newrates[[ind$y]]
  
  if(the_time<c){
    cdf=pmat_t[1,3]
  }else{
    cdf=pmat_c[1,3]+pmat_c[1,2]*pmat_t_c[2,3]+pmat_c[1,1]*pmat_t_c_new[1,3]
  }
  return(cdf)
}
```

## Finding Real World Parameters

``` {r finding-real-params, echo = FALSE}
data <- read.csv("SEERout1980_86.csv")
data$treat <- as.numeric(data$Tx)
data$treat <- factor(as.numeric(data$treat))
data$treat <- Relevel(data$treat, list("Other/none" = c(1, 2), "RP" = c(3), "RT"  =  c(4)))

data$stage <- as.numeric(data$Stage)
data$stage <- factor(data$stage)
data$stage <- Relevel(data$stage, list("Distant" = 1, "Local/regional" = c(2), "Unknown" = c(3)))
data$Prostatedeath = I(data$Prostate_death =="Dead")

KMout <- survfit(Surv(Intervals/12, Prostatedeath)~1 + strata(Race), 
                 data = subset(data, treat=="Other/none"&stage=="Local/regional"))


# Can see median survival for each group and use this to calculate
# the exponential parameter
bl_lambda <- -log(0.5)/18.3
wh_lambda <- -log(0.5)/21.8

old_bl_lambda <- log(2)/17.7
old_wh_lambda <- log(2)/21.7


inc_data <- read.csv("incidence-by-age.csv", stringsAsFactors = FALSE)
names(inc_data) <- c("age", "yeardx", "race", "rate", "count", "pop")
inc_data <- inc_data %>% filter(race %in% c("White", "Black"),
                                age != "Unknown",
                                nchar(yeardx) == 4)
inc_data <- inc_data %>% mutate(age = as.numeric(substr(age, 1, 2)),
                                yeardx = as.numeric(yeardx),
                                rate = rate/100000)
inc_data_bl <- inc_data %>% filter(race=="Black",
                                   yeardx %in% 1980:1986)

bl_pars <- inc_data_bl %>% group_by(age) %>% dplyr::summarise(incrate = mean(rate))
bl_pars <- bl_pars %>% mutate(survrate = bl_lambda)

inc_data_wh <- inc_data %>% filter(race=="White",
                                   yeardx %in% 1980:1986)

wh_pars <- inc_data_wh %>% group_by(age) %>% dplyr::summarise(incrate = mean(rate))
wh_pars <- wh_pars %>% mutate(survrate = wh_lambda)
```

## Graphing One Cohort model

``` {r graphing-one-cohort-model}
bl_dens <- seq(1, 100, 1) %>% lapply(FUN = "find_density", 
                            birth_year = 0, 
                            c = 200,
                            breakpts = bl_pars$age,
                            oldrates = bl_pars %>% get_rate_matrices(),
                            newrates = bl_pars %>% mutate(survrate = 0.1*survrate) %>% get_rate_matrices()) %>% unlist()

wh_dens <- seq(1, 100, 1) %>% lapply(FUN = "find_density", 
                            birth_year = 0, 
                            c = 200,
                            breakpts = wh_pars$age,
                            oldrates = wh_pars %>% get_rate_matrices(),
                            newrates = wh_pars %>% mutate(survrate = 0.1*survrate) %>% get_rate_matrices()) %>% unlist()

bl_cdf <- seq(1, 100, 1) %>% lapply(FUN = "find_cdf", 
                                    birth_year = 0, 
                                    c = 200,
                                    breakpts = bl_pars$age,
                           oldrates = bl_pars %>% get_rate_matrices(),
                           newrates = bl_pars %>% mutate(survrate = 0.1*survrate) %>% get_rate_matrices()) %>% unlist()

wh_cdf <- seq(1, 100, 1) %>% lapply(FUN = "find_cdf", 
                           birth_year = 0, 
                           c = 200,
                           breakpts = wh_pars$age,
                           oldrates = wh_pars %>% get_rate_matrices(),
                           newrates = wh_pars %>% mutate(survrate = 0.1*survrate) %>% get_rate_matrices()) %>% unlist()

dat <- data.frame(age = 1:100, 
                  bl_dens, 
                  wh_dens, 
                  bl_cdf, 
                  wh_cdf, 
                  wh_haz = wh_dens/(1-wh_cdf),
                  bl_haz = bl_dens/(1-bl_cdf))
dat <- dat %>% mutate(risk_rat = bl_haz/wh_haz,
                      risk_diff = bl_haz - wh_haz)
gg2 <- ggplot(data = dat, aes(x = age, y = wh_haz)) + geom_point()
print(gg2)
```

```{r real-world-one-cohort}
agemort <- read.csv("long-age-specific-mortality.csv", stringsAsFactors = FALSE)
names(agemort) <- c("race", "age", "yeardth", "rate", "count", "pop")
agemort <- agemort %>% filter(race %in% c("White", "Black"))
agemort <- agemort %>% filter(nchar(yeardth) == 4,
                                    age != "Unknown") 
agemort <- agemort %>% mutate(age = as.numeric(substr(age, 1, 2)) + 2.5,
                                    yearbth = as.numeric(yeardth) - age)

gg <- ggplot(data = agemort %>% filter(yearbth > 1915, yearbth < 1930), aes(x = age, y = rate/100000)) + geom_point(aes(color=race, group = race))
gg <- gg + geom_line(data = dat, aes(x = age, y = wh_haz)) + geom_line(data = dat, aes(x = age, y = bl_haz))
gg <- gg + facet_wrap(~yearbth)
print(gg)



gg <- ggplot(data = agemort %>% filter(yearbth > 1915, yearbth < 1930, race == "White") %>% merge(agemort %>% filter(yearbth > 1900, yearbth < 1930, race=="Black"), by = c("age", "yearbth")), aes(x = age, y =  rate.y/rate.x)) + geom_point()
gg <- gg + geom_line(data = dat, aes(x = age, y = bl_haz/wh_haz))
gg <- gg + facet_wrap(~yearbth)
print(gg)
```













